# 1st answer

In [11]:
import numpy as np
arr=np.array(range(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# 2nd answer

In [2]:
import numpy as DK

In [26]:
k=[]
l=[]

print("Enter five values for first list")
for i in range(1,6):
    x=input(i)
    k.append(x)

print("Enter five values for second list")
for i in range(1,6):
    x=input(i)
    l.append(x)

arr1=DK.array([k])
arr2=DK.array([l])


print(" ")
print(" Concatination of two arrays")
print(" ")
arr_con=DK.concatenate([arr1,arr2])
print(arr_con)

print(" ")
print("sorting")
print(" ")
print(DK.sort(arr_con))


    


Enter five values for first list


1 22
2 33
3 44
4 23
5 24


Enter five values for second list


1 55
2 66
3 77
4 56
5 57


 
 Concatination of two arrays
 
[['22' '33' '44' '23' '24']
 ['55' '66' '77' '56' '57']]
 
sorting
 
[['22' '23' '24' '33' '44']
 ['55' '56' '57' '66' '77']]


# 3rd answer

In [32]:

arr=DK.array([[ 1, 2, 3],[ 4, 5, 6],[7,8,9]])
 
print("dimension of array: ",arr.ndim)
print(" ")
print("Size of array: ",arr.size)
 



dimension of array:  2
 
Size of array:  9


# 4th answer

In [74]:
arr_re=DK.array([1,2,3,4,5,6])
print(arr_re)
print(" ")
print("1D array converted into 2D array")
re=DK.reshape(arr_re,(2,3))
print(re)
print(" ")

# DK.newaxis
row=arr_re[DK.newaxis,:]
print("one row six column")
print(row.shape)
col=arr_re[:,DK.newaxis]
print("six rows six columns")
print(col.shape)



[1 2 3 4 5 6]
 
1D array converted into 2D array
[[1 2 3]
 [4 5 6]]
 
one row six column
(1, 6)
six rows six columns
(6, 1)
